{
    "Action": "NetworkConnectionFound",
    "EventGUID": "40c149f3-9d9d-4fef-bbc6-3d855dca3944",
    "EventID": 76,
    "EventRuleName": "NetworkConnectionFound - Network Connection Info",
    "EventRulesVersion": "202410231648",
    "EventTime": "2024-10-30T10:35:12.785",
    "ServiceVersion": "1.3.0",
    "SystemAgentID": "standalone-run",
    "SystemHostname": "test",
    "SystemMachineSN": "TEST",
    "SystemOSName": "macOS 15.0.1 arm64 #24.0.0",
    "SystemOSType": "darwin",
    "customer_id": "local-stand",
    "dev_fqdn": "test",
    "dev_id": "standalone-run",
    "dev_ipv4": "1.1.1.1",
    "dev_os": "macOS 15.0.1 arm64 #24.0.0",
    "dev_os_type": "darwin",
    "dev_serial": "TEST",
    "event_id": 76,
    "event_log_source": "InventoryNG",
    "event_type": "NetworkConnectionInfo",
    "event_type_vendor": "NetworkConnectionFound",
    "event_utc_time": "2024-10-30T10:35:12.785",
    "event_uuid": "40c149f3-9d9d-4fef-bbc6-3d855dca3944",
    "inventory_op_type": "Snapshot",
    "inventory_session_id": 17302845070000003,
    "inventory_task_name": "NetworkConnectionFound - Network Connection Inventory",
    "net_conn_community_id": "D8CA471FCB61CD5A86F8C3415354E3AE1061E26E",
    "net_conn_direction": "Inbound",
    "net_dst_hostname": "localhost",
    "net_dst_ipv4": "127.0.0.1",
    "net_dst_port": 64534,
    "net_is_ipv6": false,
    "net_proto": "TCP",
    "net_src_hostname": "localhost",
    "net_src_ipv4": "127.0.0.1",
    "net_src_port": 64556,
    "proc_cmdline": "/Users/test/anaconda3/bin/python -m ipykernel_launcher -f /Users/test/Library/Jupyter/runtime/kernel-d30f45ab-2244-4b65-837a-f0ce311286f5.json",
    "proc_cwd": "/Users/test/Python",
    "proc_file_exists": true,
    "proc_file_md5": "9B5AE1F0950387C3EA0A384B2E973525",
    "proc_file_name": "python",
    "proc_file_path": "/Users/test/anaconda3/bin/python",
    "proc_file_sha256": "BF24806517587EF642679BCFF4E6EE91DF272CC1F3C3C623BD66DCAD516AA7B9",
    "proc_file_signed": false,
    "proc_group_e_id": 20,
    "proc_group_e_name": "staff",
    "proc_group_r_id": 20,
    "proc_group_r_name": "staff",
    "proc_guid": "5fec95c4-6e97-5ad2-9e66-08e6b6edde1f",
    "proc_id": 69371,
    "proc_p_cmdline": "/Users/test/anaconda3/bin/python /Users/test/anaconda3/bin/jupyter-notebook",
    "proc_p_cwd": "/Users/test",
    "proc_p_file_exists": true,
    "proc_p_file_md5": "9B5AE1F0950387C3EA0A384B2E973525",
    "proc_p_file_name": "python",
    "proc_p_file_path": "/Users/test/anaconda3/bin/python",
    "proc_p_file_sha256": "BF24806517587EF642679BCFF4E6EE91DF272CC1F3C3C623BD66DCAD516AA7B9",
    "proc_p_file_signed": false,
    "proc_p_group_e_id": 20,
    "proc_p_group_e_name": "staff",
    "proc_p_group_r_id": 20,
    "proc_p_group_r_name": "staff",
    "proc_p_guid": "59dffd6b-cd72-5727-a6ba-8da40bbff85b",
    "proc_p_id": 69351,
    "proc_p_term_name": "/dev/ttys005",
    "proc_p_term_session_id": 0,
    "proc_p_uptime": 766278,
    "proc_p_usr_audit_id": 0,
    "proc_p_usr_audit_name": "root",
    "proc_p_usr_e_id": 502,
    "proc_p_usr_e_name": "test",
    "proc_p_usr_r_id": 502,
    "proc_p_usr_r_name": "test",
    "proc_term_session_id": 0,
    "proc_uptime": 766262,
    "proc_usr_audit_id": 0,
    "proc_usr_audit_name": "root",
    "proc_usr_e_id": 502,
    "proc_usr_e_name": "test",
    "proc_usr_r_id": 502,
    "proc_usr_r_name": "test",
    "rule_name": "NetworkConnectionFound - Network Connection Info",
    "sensor_cfg_profile": "triage",
    "sensor_cfg_profile_id": "60",
    "sensor_cfg_version": "202410231648",
    "sensor_version": "1.3.0"
}